import React, { useState, useRef, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { contact, brand } from './config';
import './styles.css';

const projects = [
 { id:'distrito', name:'Distrito 13', suffix:'Barbearia', category:'Barbearia · Site institucional', url:'https://distrito13-barbearia.pages.dev', color:'#b99360', description:'Projeto institucional desenvolvido para apresentar serviços, equipe e identidade de uma barbearia com uma estética urbana e moderna.', objective:'Comunicar personalidade e apresentar os serviços de forma clara.', solution:'Uma apresentação de identidade urbana, com espaço para serviços e equipe.' },
 { id:'brasa', name:'Brasa 77', suffix:'Burger', category:'Hamburgueria · Site comercial', url:'https://brasa77-burger.pages.dev', color:'#ef9b56', description:'Site criado para apresentar uma hamburgueria com uma identidade visual forte, foco nos produtos e experiência otimizada para dispositivos móveis.', objective:'Dar protagonismo aos produtos e facilitar a descoberta do negócio.', solution:'Uma direção visual marcante e uma experiência pensada para o celular.' },
 { id:'vittavet', name:'VittaVet', suffix:'Clínica Veterinária', category:'Clínica veterinária · Site institucional', url:'https://vittavet-clinica.pages.dev', color:'#86bdad', description:'Projeto criado para transmitir confiança e acolhimento, apresentando serviços, equipe, estrutura, informações e opções de contato.', objective:'Apresentar cuidados e serviços com clareza e acolhimento.', solution:'Uma organização que aproxima informações, serviços e opções de contato.' }
];
const services = [ ['01','Sites institucionais','Seu negócio bem apresentado.','Sites profissionais para apresentar sua empresa, seus serviços e as formas de contato.'], ['02','Landing pages','Uma página. Um objetivo claro.','Páginas focadas em apresentar uma oferta, um produto ou um serviço.'], ['03','Negócios locais','A sua região também está online.','Sites para restaurantes, barbearias, clínicas, pet shops, lojas e prestadores de serviço.'], ['04','Design responsivo','Bom em qualquer tela.','Experiências adaptadas para celulares, tablets e computadores, com atenção especial ao mobile.'], ['05','Identidade visual para web','Uma presença com personalidade.','Uma apresentação digital coerente com a essência e o tipo do seu negócio.'], ['06','Elementos visuais e 3D','Um detalhe que faz diferença.','Elementos personalizados com Blender quando o projeto pede uma experiência visual diferenciada.'] ];
const steps = [['Entendimento','Conhecer seu negócio, seu público e o que você espera do site.'],['Criação','Dar forma à estrutura, à identidade e à experiência digital.'],['Ajustes','Revisar os detalhes e refinar o projeto até a versão final.'],['Publicação','Preparar o site e colocá-lo online, pronto para ser apresentado.']];
const nav = [['Projetos','projetos'],['Serviços','servicos'],['Processo','processo'],['Sobre','sobre'],['Contato','contato']];
function Arrow({diagonal=false}) { return <span aria-hidden="true">{diagonal?'↗':'↗'}</span> }
function ProjectScreen({project, hero=false}) {
 const [failed,setFailed] = useState(false);
 return <div className={`screen ${project.id}`} style={{'--project':project.color}}><div className="screen-bar"><span className="window-dots" aria-hidden="true">● ● ●</span><span>{new URL(project.url).hostname}</span><span aria-hidden="true">↗</span></div>{!failed ? <img src={`${import.meta.env.BASE_URL}projects/${project.id}.webp`} alt={`Captura do site ${project.name} ${project.suffix}`} width="1440" height="900" loading={hero?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/> : <div className="project-cover"><span>PROJETO DEMONSTRATIVO</span><strong>{project.name}<br/><em>{project.suffix}</em></strong><span>Conheça o projeto ao vivo ↗</span></div>}</div>
}
function ContactForm() {
 const [draft,setDraft] = useState(''); const [status,setStatus] = useState(''); const output=useRef(null);
 function submit(e) {e.preventDefault(); const f=new FormData(e.currentTarget);setDraft(`Olá, Bruno! Gostaria de conversar sobre um projeto.\n\nNome: ${f.get('nome')}\nEmpresa: ${f.get('empresa')||'Não informada'}\nContato: ${f.get('contato')}\nTipo de projeto: ${f.get('tipo')}\n\n${f.get('mensagem')}`);setStatus('Mensagem preparada. Nenhuma informação foi enviada.');}
 useEffect(()=>{if(draft) output.current?.focus()},[draft]);
 async function copy(){try{await Promise.race([navigator.clipboard.writeText(draft),new Promise((_,reject)=>setTimeout(()=>reject(new Error('clipboard unavailable')),1800))]);setStatus('Mensagem copiada. Nenhuma informação foi enviada.')}catch{output.current?.focus();output.current?.select();setStatus('Selecione e copie a mensagem abaixo.')}}
 return <form onSubmit={submit} className="contact-form"><div className="form-top"><h3>Conte sobre sua ideia</h3><span>Vamos começar pelo essencial.</span></div><div className="form-grid"><label>Nome <span>*</span><input name="nome" autoComplete="name" placeholder="Como você se chama?" required maxLength={100}/></label><label>Empresa<input name="empresa" autoComplete="organization" placeholder="Nome do seu negócio" maxLength={150}/></label><label>WhatsApp ou e-mail <span>*</span><input name="contato" autoComplete="email" placeholder="Seu melhor contato" required maxLength={150}/></label><label>Tipo de projeto <span>*</span><select name="tipo" required defaultValue=""><option value="" disabled>Selecione uma opção</option><option>Site institucional</option><option>Landing page</option><option>Site para negócio local</option><option>Ainda não sei</option></select></label></div><label>Mensagem <span>*</span><textarea name="mensagem" rows={4} placeholder="O que você gostaria de criar?" required maxLength={3000}/></label><p className="form-note">Prepare sua mensagem aqui. O formulário não realiza envios.</p><button className="button primary" type="submit">Preparar mensagem <Arrow/></button>{draft&&<div className="draft"><label>Mensagem pronta para copiar<textarea ref={output} readOnly value={draft} rows={9}/></label><button type="button" className="button secondary" onClick={copy}>Copiar mensagem</button></div>}<p role="status" className="status">{status}</p></form>
}
function App(){
 const [menu,setMenu]=useState(false); const menuButton=useRef(null); const mobileNav=useRef(null);
 useEffect(()=>{if(!menu)return;const listener=e=>{if(e.key==='Escape'){setMenu(false);menuButton.current?.focus()}}; document.addEventListener('keydown',listener);return()=>document.removeEventListener('keydown',listener)},[menu]);
 useEffect(()=>{if(!menu)return;const handle=e=>{if(!mobileNav.current?.contains(e.target)&&!menuButton.current?.contains(e.target))setMenu(false)};document.addEventListener('pointerdown',handle);return()=>document.removeEventListener('pointerdown',handle)},[menu]);
 return <><a className="skip-link" href="#main">Pular para o conteúdo</a><header><div className="container header-inner"><a className="brand" href="#inicio" aria-label="Bruno, início">{brand.name.toLowerCase()}<span className="brand-dot">.</span><span className="brand-role">DESENVOLVIMENTO WEB</span></a><nav aria-label="Navegação principal" className="desktop-nav">{nav.map(([label,id])=><a href={`#${id}`} key={id}>{label}</a>)}</nav><a className="button header-cta" href="#contato">Solicitar orçamento <Arrow/></a><button ref={menuButton} className="menu-toggle" aria-expanded={menu} aria-controls="mobile-nav" aria-label={menu?'Fechar menu':'Abrir menu'} onClick={()=>setMenu(!menu)}>{menu?'Fechar ×':'Menu ☰'}</button></div><nav ref={mobileNav} id="mobile-nav" aria-label="Navegação móvel" className="mobile-nav" hidden={!menu}>{nav.map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}<a href="#contato" onClick={()=>setMenu(false)}>Solicitar orçamento ↗</a></nav></header>
 <main id="main"><section className="hero container" id="inicio"><div className="hero-copy"><p className="eyebrow"><span className="tiny-mark"/> DESIGN COM PROPÓSITO. PRESENÇA COM IMPACTO.</p><h1>Sites modernos para negócios que querem ser <em>levados a sério.</em></h1><p className="lead">Crio experiências digitais rápidas, responsivas e profissionais para empresas que querem melhorar sua presença na internet.</p><div className="hero-actions"><a className="button primary" href="#projetos">Ver meus projetos <Arrow/></a><a className="text-link" href="#contato">Vamos conversar <Arrow/></a></div><div className="hero-note"><span>Design personalizado</span><i/><span>Pensado para o celular</span></div></div><div className="hero-visual" aria-label="Apresentação dos projetos demonstrativos"><div className="visual-grid"/><div className="floating-label"><span className="cross">✦</span> Cada negócio, uma identidade.</div><div className="hero-screen hero-screen-back"><ProjectScreen project={projects[2]} hero/></div><div className="hero-screen hero-screen-main"><ProjectScreen project={projects[0]} hero/></div><div className="hero-screen hero-screen-front"><ProjectScreen project={projects[1]} hero/></div><div className="visual-caption"><span>DO CONCEITO À PRESENÇA DIGITAL</span><span>01 — 03</span></div></div></section>
 <div className="principles container"><span>Uma boa presença digital começa com</span><strong>Design que representa.</strong><strong>Clareza que aproxima.</strong><strong>Experiência que funciona.</strong></div>
 <section id="projetos" className="section container"><div className="section-heading"><div><p className="eyebrow">01 / TRABALHOS SELECIONADOS</p><h2>Projetos em <em>destaque.</em></h2></div><p>Negócios diferentes.<br/>Identidades que fazem sentido para cada um.</p></div><p className="demo-note">Os projetos apresentados neste portfólio são projetos demonstrativos criados para estudo, prática e apresentação profissional.</p><div className="projects">{projects.map((p,i)=><article key={p.id} className={`project project-${p.id}`}><div className="project-image"><a href={p.url} target="_blank" rel="noopener noreferrer" aria-label={`Ver ${p.name} ${p.suffix} ao vivo, abre em nova aba`}><ProjectScreen project={p}/></a><div className="project-image-caption"><span>DEMONSTRATIVO / {String(i+1).padStart(2,'0')}</span><span>WEB DESIGN · DESENVOLVIMENTO</span></div></div><div className="project-body"><p className="category">{p.category}</p><h3>{p.name} <span>{p.suffix}</span></h3><p>{p.description}</p><div className="case-details"><div><h4>Objetivo</h4><p>{p.objective}</p></div><div><h4>Solução</h4><p>{p.solution}</p></div></div><a className="project-link" href={p.url} target="_blank" rel="noopener noreferrer">Ver projeto ao vivo <Arrow/></a></div></article>)}</div></section>
 <section id="servicos" className="section services-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">02 / O QUE EU CRIO</p><h2>Como posso ajudar<br/><em>seu negócio.</em></h2></div><p>Da primeira página a uma presença completa.<br/>O formato certo para o seu objetivo.</p></div><div className="services-grid">{services.map(([n,title,tag,description])=><article className="service" key={n}><span className="service-number">{n}</span><h3>{title}</h3><h4>{tag}</h4><p>{description}</p></article>)}</div></div></section>
 <section className="section container benefits"><div><p className="eyebrow">BOM DESIGN VAI ALÉM DA APARÊNCIA</p><h2>Bonito de ver.<br/><em>Fácil de usar.</em></h2><p className="section-intro">Cada escolha tem um propósito: criar um site que represente bem seu negócio e torne a experiência mais simples.</p></div><div className="benefit-list">{[['Rápido','Sites pensados para carregar rapidamente e oferecer uma boa experiência.'],['Responsivo','Uma navegação confortável em qualquer tela, principalmente no celular.'],['Visual personalizado','Uma direção visual adequada à personalidade e ao público do seu negócio.'],['Estrutura moderna','Tecnologias atuais e infraestrutura de publicação como a Cloudflare.'],['Pronto para estar online','O projeto pode ser preparado e publicado para você compartilhar.']].map(([title,text])=><article key={title}><span className="check" aria-hidden="true">✓</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
 <section id="processo" className="section container process"><div className="section-heading"><div><p className="eyebrow">03 / UM CAMINHO CLARO</p><h2>Do primeiro contato<br/>ao <em>site publicado.</em></h2></div><p>Você acompanha a construção.<br/>Eu cuido de transformar a ideia em experiência.</p></div><ol className="process-grid">{steps.map(([title,text],i)=><li key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
 <section id="sobre" className="section container about"><div className="about-title"><p className="eyebrow">04 / POR TRÁS DOS PROJETOS</p><h2>Desenvolvimento.<br/>Design.<br/><em>Personalidade.</em></h2><span className="signature">Bruno<span>↗</span></span></div><div className="about-copy"><p className="about-lead">Uma presença profissional começa com atenção aos detalhes.</p><p>Desenvolvo experiências digitais para negócios que querem ter uma presença mais profissional na internet. Gosto de combinar desenvolvimento web, design e recursos visuais para criar projetos que sejam bonitos, rápidos e fáceis de usar.</p><p>Além do desenvolvimento web, exploro ferramentas de criação 3D como Blender para projetos que pedem uma identidade visual ainda mais personalizada.</p><div className="tech"><span>FERRAMENTAS QUE FAZEM PARTE DO PROCESSO</span><div>{['React','Vite','JavaScript','HTML','CSS','GitHub','Cloudflare','Blender'].map(t=><span key={t}>{t}</span>)}</div></div></div></section>
 <section className="container"><div className="final-cta"><p className="eyebrow">VAMOS CRIAR SUA PRÓXIMA PRESENÇA DIGITAL?</p><h2>Seu negócio também<br/>pode ter um <em>site assim.</em></h2><p>Se você quer uma presença online mais moderna e profissional,<br className="desktop-break"/> podemos conversar sobre seu projeto.</p><a className="button light" href="#contato">Vamos conversar <Arrow/></a><span className="cta-decoration" aria-hidden="true">↗</span></div></section>
 <section id="contato" className="section container contact-section"><div><p className="eyebrow">05 / VAMOS CONVERSAR</p><h2>Uma boa ideia<br/>merece <em>um começo.</em></h2><p className="section-intro">Conte um pouco sobre o seu negócio e o que você tem em mente.</p><div className="contact-links">{contact.whatsapp&&<a href={`https://wa.me/${contact.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noopener noreferrer">WhatsApp <Arrow/></a>}{contact.email&&<a href={`mailto:${contact.email}`}>E-mail <Arrow/></a>}{contact.instagram&&<a href={contact.instagram} target="_blank" rel="noopener noreferrer">Instagram <Arrow/></a>}{!contact.whatsapp&&!contact.email&&!contact.instagram&&<p>Os canais de contato estarão disponíveis em breve. Por enquanto, você pode preparar e copiar sua mensagem.</p>}</div></div><ContactForm/></section></main>
 <footer className="container"><div className="footer-top"><a href="#inicio" className="brand">{brand.name.toLowerCase()}<span className="brand-dot">.</span></a><p>Desenvolvimento web e experiências digitais.</p><nav aria-label="Rodapé"><a href="#projetos">Projetos</a><a href="#servicos">Serviços</a><a href="#contato">Contato</a>{contact.github&&<a href={contact.github} target="_blank" rel="noopener noreferrer">GitHub ↗</a>}{contact.instagram&&<a href={contact.instagram} target="_blank" rel="noopener noreferrer">Instagram ↗</a>}</nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {brand.name}</span><a href="#inicio">Voltar ao topo ↑</a></div></footer></>;
}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
